import { getBaseUrl } from "../../config";
import { generateRandomString } from "./utils";

const baseUrl = getBaseUrl();

export default {
    loginUrl: `${baseUrl}/auth/login`,
    homeUrl: `${baseUrl}/cms/solar/portfolio/home`,
};

export const unitVariables = {
    Placeholder: "Input Unit Name",
    CreateSuccess: "Unit Added Successfully!!",
    Select: "Control+A",
    Delete: "Backspace",
    Alert: "Please Input Unit Name!",
    UpdateSuccess: "Unit Updated Successfully!!",
    DeleteSuccess: "Unit Deleted Successfully!!"
};

export const jobTagVariables = {
    operation: {
        create: "Add",
        save: "Save",
        Confirm: "OK",
    },
    Placeholder: "Job Tag Name",
    CreateSuccess: "Job tag Added successfully!!",
    Select: "Control+A",
    Delete: "Backspace",
    Alert: "Please input Job Tag Name!",
    JobTagAlertPrefix: "Job Tag ",
    JobTagAlertSuffix: " already exists.",
    DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
    DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']",
    DeleteSuccess: "Job Tag Removed successfully!!",
    
};

export const formTagVariables = {
    operation: {
        create: "Add",
        save: "Submit",
        Confirm: "OK",
    },
    Placeholder: 'Input Form Tag Name',
    CreateSuccess: "Form Tag Added successfully!!",
    UpdateSuccess: "Form Tag Updated successfully!!",
    Select: "Control+A",
    Delete: "Backspace",
    Alert: "Please Input Form Tag Name!",
    FormTagAlertPrefix: "Tag with this Form Tag Name /",
    FormTagAlertSuffix: "/ already exists.",
    DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
    DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']",
    DeleteSuccess: "Form Tag Removed successfully!!",

    
};


export const storeVariables = {
    NamePlaceholder: "Input Store Name",
    CodePlaceholder: "Input Store Code",
    StorekeeperPlaceholder: "Select Storekeeper",
    PlantdropdownSelector: "#screencontainer > div > app-store-create > div > div > nz-card > div.ant-card-body > div:nth-child(2) > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
    StorekeeperdropdownSelector: "#screencontainer > div > app-store-create > div > div > nz-card > div.ant-card-body > div:nth-child(2) > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
    StreetOnePlaceholder: "Input Street1",
    StreetTwoPlaceholder: "Input Street2",
    CityPlaceholder: "Input City",
    CountryPlaceholder: "Input Country",
    StatePlaceholder: "Input State",
    PincodePlaceholder: "Input Pincode",
    RegionPlaceholder: "Input Region",
    LatitudePlaceholder: "Input Latitude",
    LongitudePlaceholder: "Input Longitude",
    GoogleMapLinkPlaceholder: "Input Google Map Link",
    SubmitbuttonSelector: "#screencontainer > div > app-store-create > div > div > nz-card > div.ant-card-body > div.steps-action.ng-star-inserted > nz-space > div:nth-child(2) > button > span",
    CreateSuccessSelector: "#cdk-overlay-34 > nz-notification-container > div.ant-notification.ant-notification-topRight > nz-notification > div > div > div > div",
    CreateSuccess: "Store Created Successfully!!",
    Enter: "Enter",
    Select: "Control+A",
    Delete: "Backspace",
    NameAlert: "Please Input Store Name!",
    CodeAlert: "Please Input Store Code",
    CodeSizeAlert: "Enter a code of only 8 letters",
    PlantAlert: "Please Select Plant!",
    StorekeeperAlert: "Please Select Storekeeper!",
    StreetOneAlert: "Please Input Street1!",
    StreetTwoAlert: "Please Input Street2!",
    CityAlert: "Please Input City!",
    CountryAlert: "Please Input Country!",
    StateAlert: "Please Input State!",
    PincodeAlert: "Please Input Pincode!",
    RegionAlert: "Please Input Region!",
    LatitudeAlert: "Please Input Latitude!",
    LongitudeAlert: "Please Input Longitude!",
    GoogleMapLinkAlert: "Please Input Google Map Link!",
    UpdateSuccess: "Store Updated Successfully!!",
    NameExistValidation: "Store name already exist",
    DeleteSuccess: "Store Deleted Successfully!!",
    operation: {
        create: "Add",
        submit: "Submit"
    }
};

export const vendor_Type_Variables = {
    operation: {
        create: "Add",
        save: "Save",
        Cancel: "Cancel"
    },
    NamePlaceholder: "Input Vendor Type Name",
    CodePrefixPlaceholder: "Input Vendor Code Prefix",
    FormDropdownLocator: '.ant-select[formcontrolname="formid"][nzplaceholder="Select Form"]',
    CreateSuccess: "Vendor Type Created Successfully!!",
    UpdateSuccess: "Vendor Type Updated Successfully!!",
    Enter: "Enter",
    Select: "Control+A",
    Delete: "Backspace",
    NameAlert: "Please Input Vendor Type Name!",
    CodePrefixSizeAlert: "Only Alphabets And Numbers Can Contain Spaces ,- And Underscore",
    CodePrefixAlert: "Please Input Vendor Code Prefix!",
    FormAlert: "Please Select Form!",
    FormCancelSelector: "#screencontainer > div > app-create-vendor-type > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-dirty.ng-touched > div > div:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    FormEditCancelSelector: 'span[nztype="close-circle"]',
    NameExistAlert: "vendortype name - ",
    NameExistalert: " already exist",
    CodePrefixExistAlert: "vendorcode prefix - ",
    CodePrefixExistalert: " already exist",
    randomCodePrefix: generateRandomString(5),

};

export const part_Type_Variables = {
    operation: {
        create: "Add",
        save: "Save",
        Cancel: "Cancel"
    },
    NamePlaceholder: "Input Part Type Name",
    CodePrefixPlaceholder: "Input Stock Code Prefix",
    randomCodePrefix: generateRandomString(5),
    FormDropdownLocator: '.ant-select[formcontrolname="formid"][nzplaceholder="Select Form"]',
    UnitDropdownLocator: '.ant-select[formcontrolname="unit"][nzplaceholder="Select Unit"]',
    LowerQuantityThresholdPlaceholder: "Input Lower Quantity Threshold",
    UpperQuantityThresholdPlaceholder: "Input Upper Quantity Threshold",
    BatchLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(7) > nz-form-item > nz-switch > button",
    SelectAssetTypeLocator: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-transfer > nz-transfer-list:nth-child(1) > div.ant-transfer-list-header > label > span.ant-checkbox > input",
    SelectSingleAssetTypeLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-transfer > nz-transfer-list:nth-child(1) > div.ant-transfer-list-body.ant-transfer-list-body-with-search > ul > li:nth-child(1) > label > span.ant-checkbox > input",
    SelectSingleDeviceTypeLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-transfer > nz-transfer-list:nth-child(1) > div.ant-transfer-list-body.ant-transfer-list-body-with-search > ul > li:nth-child(1) > label > span.ant-checkbox > input",
    SelectAssetTypeNextLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-transfer > div > button:nth-child(2) > span > svg > path",
    EditAssetTypeNextLocator: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-transfer > div > button:nth-child(2) > span > svg",
    SelectDeviceTypeLocator: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-transfer > nz-transfer-list:nth-child(1) > div.ant-transfer-list-header > label > span.ant-checkbox > input",
    SelectDeviceTypeNextLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-transfer > div > button:nth-child(2) > span > svg",
    EditDeviceTypeNextLocator: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-transfer > div > button:nth-child(2) > span > svg",
    FormCancelSelector: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(5) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    UnitCancelSelector: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(8) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    EditFormCancelSelector: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-star-inserted.ng-dirty.ng-invalid.ng-touched > div > div:nth-child(5) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    EditUnitCancelSelector: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-star-inserted.ng-dirty.ng-invalid.ng-touched > div > div:nth-child(8) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    EditBatchLocator: 'nz-switch[formcontrolname="isbatch"] button.ant-switch-checked',
    CreateSuccess: "Part Type Created Successfully!!",
    UpdateSuccess: "Part Type Updated Successfully!!",
    Enter: "Enter",
    Select: "Control+A",
    Delete: "Backspace",
    NameAlert: "Please Input Part Type Name!",
    CodePrefixAlert: "Please Input Stock Code Prefix!",
    LowerThresholdAlert: "Invalid threshold!",
    UpperThresholdAlert: "Invalid threshold!",
    FormAlert: "Please Select Form!",
    UnitAlert: "Please Select Unit!",
    NameExistAlert: "parttype name - ",
    NameExistalert: " already exist",
    CodePrefixExistAlert: "stockcode prefix - ",
    CodePrefixExistalert: " already exist",
    DisableText: "Disable Part Type",
    DisableSuccess: "Part Type Disabled Successfully!",
    EnableText: "Enable Part Type",
    EnableSucess: "Part Type Enabled Successfully!",
    };

    export const storage_Location_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Cancel: "Cancel"
        },
        NamePlaceholder: "Input Storage location Name",
        StoreDropdownLocator: '.ant-select[formcontrolname="storeid"][nzplaceholder="Select Store"]',
        StoreCancelLocator: 'svg[data-icon="close-circle"]',
        CreateSuccess: "Storage Location Submitted Successfully!!",
        UpdateSuccess: "Storage Location Updated Successfully!!",
        Enter: "Enter",
        Select: "Control+A",
        Delete: "Backspace",
        StoreAlert: "Please Select a Store!",
        NameAlert: "Please Input Storage Location Name!",
        NameExistValidation: "Storage Location name already exist",
        DisableText: "Disable Storage Location",
        DisableSuccess: "Storage Location Disabled Successfully!",
        EnableText: "Enable Storage Location",
        EnableSucess: "Storage Location Enabled Successfully!",
    };

    export const asset_Type_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Cancel: "Cancel",
            Confirm: "OK",
        },
        NamePlaceholder: "Input Asset Type Name",
        CodePrefixPlaceholder: "Input Asset Type Code Prefix",
        FormDropdownLocator: '.ant-select[formcontrolname="formid"][nzplaceholder="Select Form"]',
        CreateSuccess: "Asset Type Created Successfully!!",
        UpdateSuccess: "Asset Type Updated Successfully!!",
        Enter: "Enter",
        Select: "Control+A",
        Delete: "Backspace",
        NameAlert: "Please Input Asset Type Name!",
        NameSizeAlert: "No of characters should be greater than 3!",
        CodePrefixSizeAlert: "Only Alphabets and numbers are allowed Enter a code of only 5 character",
        CodePrefixAlert: "Please Input Asset Type Code Prefix!",
        FormAlert: "Please Select Form!",
        FormCancelSelector: "#screencontainer > div > ng-component > div > div > nz-card > div.ant-card-body > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormEditCancelSelector: 'span[nztype="close-circle"]',
        NameExistAlert: "Asset Type Name ",
        NameExistalert: " already exist",
        CodePrefixExistAlert: "Asset Type Code prefix ",
        CodePrefixExistalert: " already exist",
        randomCodePrefix: generateRandomString(5),
        DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
        DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']",
        DeleteSuccess: "Asset Type Deleted Successfully!!",
    
    };

    export const approval_matrix_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Confirm: "OK",
        },
        NamePlaceholder: "Input Approval Matrix Name",
        LabelPlaceholder: "Input Approval Label",
        NextButtonLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > ul > li.next > button > span:nth-child(1)",
        LabelOneLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(1) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormOneRequiredLocator: "nz-switch[formcontrolname='formrequired']",
        FormOneDropdownLocator: '#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(1) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input',
        PlusOneLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div > form > nz-card > div.ant-card-head.ng-star-inserted > div > div.ant-card-extra.ng-star-inserted > nz-space > div:nth-child(1) > span > button > span > svg",
        LabelTwoLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormTwoRequiredLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-switch > button",
        FormTwoDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        PlusTwoLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-head.ng-star-inserted > div > div.ant-card-extra.ng-star-inserted > nz-space > div:nth-child(1) > span > button > span > svg",
        LabelThreeLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormThreeRequiredLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-switch > button",
        FormThreeDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        PlusThreeLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-head.ng-star-inserted > div > div.ant-card-extra.ng-star-inserted > nz-space > div:nth-child(1) > span > button > span > svg",
        LabelFourLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormFourRequiredLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-switch > button",
        FormFourDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        PlusFourLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-head.ng-star-inserted > div > div.ant-card-extra.ng-star-inserted > nz-space > div:nth-child(1) > span > button > span > svg",
        LabelFiveLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormFiveRequiredLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-switch > button",
        FormFiveDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        FormOneEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(1) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        FormTwoEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        FormThreeEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        FormFourEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        FormFiveEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        FormOneEditCancelLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(1) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormTwoEditCancelLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormThreeEditCancelLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormFourEditCancelLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormFiveEditCancelLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        LabelTwoAlertLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control",
        LabelThreeAlertLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control",
        LabelFourAlertLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control",
        LabelFiveAlertLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control",
        FormTwoEditAlertLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control",
        FormThreeEditAlertLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control",
        FormFourEditAlertLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control",
        FormFiveEditAlertLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control",
        CreateSuccess: "Approval Matrix Created Successfully!!",
        UpdateSuccess: "Approval Matrix Updated Successfully!!",
        Enter: "Enter",
        Select: "Control+A",
        Delete: "Backspace",
        Down: "ArrowDown",
        NameAlert: "Please Input Approval Matrix Name!",
        LabelOneAlert: "Please Input Approval Label!",
        FormAlert: "Please Select Form !",
        FormOneCancelSelector: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormTwoCancelSelector: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormEditCancelSelector: 'span[nztype="close-circle"]',
        PaginationLocator: "#screencontainer > div > app-approval-matrix-dashboard > div > div > nz-card > div.ant-card-body > nz-table > nz-spin > div > nz-pagination > ul > li.ant-pagination-options.ng-star-inserted > nz-select > nz-select-top-control > nz-select-item",
        MatrixNameExistAlert: "Approval matrix name ",
        MatrixNameExistalert: " exist",
        DuplicateApprovalLabelAlert: "Duplicate approval approvallabel added",
        DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
        DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']",
        DeleteSuccess: "Approval Matrix Deleted Successfully!!",
    
    };

    export const asset_tag_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Confirm: "OK",
        },
        Placeholder: "Asset Tag Name",
        CreateSuccess: "Asset Tag Created Successfully!!",
        Select: "Control+A",
        Delete: "Backspace",
        Alert: "Please Input Asset Tag Name",
        AssetTagExistAlert: "Asset Tag ",
        AssetTagExistalert: " already exists.",
        AssetTagNameValidation: "@asset_tag_name",
        AssetTagNameAlert: "Must start with a letter Only lowercase alphanumeric letters and _ allowed",
        DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
        DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']",
        DeleteSuccess: "Asset Tag Removed successfully!!",
    };

    export const incident_type_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Cancel: "Cancel",
            Confirm: "OK",
        },
        NamePlaceholder: "Input Incident Type Name",
        CodeLocator: 'input[formcontrolname="incidenttypecode"][placeholder="Input Incident Type Code"]',
        CodeEditLocator: "input[placeholder='Input Incident Type Code']",
        CodePrefixPlaceholder: "Input Incident Type Code Prefix",
        randomCodePrefix: generateRandomString(5),
        randomImproperCodePrefix: generateRandomString(4),
        randomCode: generateRandomString(8),
        randomImproperCode: generateRandomString(7),
        AssetTypeDropdownLocator: "[nzplaceholder='Select Asset Type'][formcontrolname='assettype']",
        AssetDropdownLocator: 'nz-select[formcontrolname="asset"]',
        FormLocator:'nz-select[formcontrolname="formid"]',
        AssetTypeEditDropdownLocator: "nz-select[nzplaceholder='Select Asset Type']",
        AssetEditDropdownLocator: "nz-select[nzplaceholder='Select Asset']",
        FormEditDropdownLocator: "nz-select[nzplaceholder='Select Form']",
        AssetTypeCancelDropdownLocator: "#screencontainer > div > app-create-incident-type > div > div > div > nz-card > div.ant-card-body > div.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div:nth-child(2) > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        AssetCancelDropdownLocator: "#screencontainer > div > app-create-incident-type > div > div > div > nz-card > div.ant-card-body > div.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div:nth-child(3) > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        FormCancelLocator: "#screencontainer > div > app-create-incident-type > div > div > div > nz-card > div.ant-card-body > div.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div:nth-child(3) > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        AssetTypeEditCancelDropdownLocator: "#screencontainer > div > app-create-incident-type > div > div > div > nz-card > div.ant-card-body > div.ng-star-inserted.ng-dirty.ng-invalid.ng-touched > div:nth-child(2) > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        AssetEditCancelDropdownLocator: "#screencontainer > div > app-create-incident-type > div > div > div > nz-card > div.ant-card-body > div.ng-star-inserted.ng-dirty.ng-invalid.ng-touched > div:nth-child(3) > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        FormEditCancelDropdownLocator: "#screencontainer > div > app-create-incident-type > div > div > div > nz-card > div.ant-card-body > div.ng-star-inserted.ng-dirty.ng-invalid.ng-touched > div:nth-child(3) > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        CreateSuccess: "Incident Type Created Successfully!!",
        UpdateSuccess: "Incident Type Updated Successfully!!",
        Select: "Control+A",
        Delete: "Backspace",
        Down: "ArrowDown",
        Alert: "Please Input Asset Tag Name",
        Enter: "Enter",
        NameAlert: "Please Input Incident Type Name!",
        CodeAlert: "Enter a code of only 8 letters !",
        ImproperCodePrefixAlert: "Enter a code of only 5 characters!",
        CodePrefixAlert: "Please Input Incident Type Code Prefix!",
        AssetTypeAlert: "Please Select Asset Type!",
        AssetAlert: "Please Select Asset!",
        FormAlert: "Please Select Form!",
        NameExistAlertPrefix: "Incident Type Name ",
        NameExistAlertSuffix: " already exist",
        CodePrefixExistAlertPrefix: "Incident code prefix ",
        CodePrefixExistAlertSuffix: " already exist", 
        DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
        DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']",
        DeleteSuccess: "Incident Type Removed successfully!!",
    };

    export const incident_tag_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Confirm: "OK",
        },
        Placeholder: "Incident Tag Name",
        CreateSuccess: "Incident Tag Created Successfully!!",
        HoverLocator: 'nz-form-label svg',
        HoverAlert: "Only Alphabets numbers and _ allowed",
        Select: "Control+A",
        Delete: "Backspace",
        Alert: "Please Input Incident Tag Name",
        AssetTagExistAlertPrefix: "Incident Tag Name ",
        AssetTagExistAlertSuffix: " already exists.",
        AssetTagNameValidation: "@Incident_tag_name",
        AssetTagNameAlert: "Must start with a letter Only lowercase alphanumeric letters and _ allowed",
        DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
        DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']",
        DeleteSuccess: "Incident Tag Removed successfully!!",
    };


    export const incident_user_map_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Confirm: "OK",
        },
        Down: "ArrowDown",
        Enter: "Enter",
        Plant: "CSBPL250MW",
        randomCode: generateRandomString(8),
        randomCodePrefix: generateRandomString(5),
        PlantLocator: "nz-select[formcontrolname='plantid'][nzplaceholder='Select Plant']",
        IncidentTypeLocator: "nz-select[formcontrolname='incidenttypeid'][nzplaceholder='Select Incident Type Name']",
        IncidenCreatorsLocator: "nz-select[formcontrolname='incidentcreators'][nzplaceholder='Select Incident Creators'][nzmode='multiple']",
        IncidentWatchersLocator: "#screencontainer > div > app-incident-user-map-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(4) > nz-form-item > nz-form-control > div > div > nz-select",
        CreateSuccess: "Incident User Map Created Successfully!!",
        UpdateSuccess: "Incident User Map Updated Successfully!!",
        PlantCancelLocator: "#screencontainer > div > app-incident-user-map-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        IncidentTypeCancelLocator: "#screencontainer > div > app-incident-user-map-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        IncidentCreatorsCancelLocator: "#screencontainer > div > app-incident-user-map-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        IncidentWatchersCancelLocator: "#screencontainer > div > app-incident-user-map-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(4) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        PlantAlert: "Please Select Plant!",
        IncidentTypeAlert: "Please Select Incident Type Name!",
        IncidentCreatorsAlert: "Please Select Incident Creators!",
        IncidentWatcherAlert: "Please Select Incident Watchers!",
        EditLocatorPrefix: "tr.ant-table-row.ng-star-inserted:has-text(",
        EditLocatorSuffix: ") app-component-display.cursor.ng-star-inserted",
        PlantEditLocator: "#screencontainer > div > app-incident-user-map-edit > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-untouched.ng-pristine.ng-star-inserted.ng-valid > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select",
        IncidentTypeEditLocator: "nz-select[formcontrolname='incidenttypeid'][nzplaceholder='Select Incident Type Name']",
        IncidentCreatorsEditLocator: "nz-select[formcontrolname='incidentcreators'][nzplaceholder='Select Incident Creators'][nzmode='multiple']",
        CreatorsSlectAllLocator: 'button.ant-btn.ant-btn-primary.ant-btn-sm.ant-btn-block:has-text("Select All")',
        IncidentWatchersEditLocator: "nz-select[formcontrolname='incidentwatchers']",
        PlanteditCancelLocator: "#screencontainer > div > app-incident-user-map-edit > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-untouched.ng-pristine.ng-star-inserted.ng-valid > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        IncidentTypeEditCancelLocator: "nz-select[nzplaceholder='Select Incident Type Name'] nz-select-clear svg",
        IncidentCreatorsEditCancelLocator: "nz-select[nzplaceholder='Select Incident Creators'] nz-select-clear svg",
        IncidentWatchersEditCancelLocator: "nz-select[formcontrolname='incidentwatchers'] nz-select-clear svg",
        IncidentUserMapExistAlert: "Incident User Map with this Incident Type and Plant Already Exist",
        DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
        DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']",
        DeleteSuccess: "Incident User Map Deleted Successfully!!",

    };

    export const label_meta_Variables = {
        operation: {
            save: "Save",
        },
        AssigneesPlaceholder: "Input Assignees",
        AssignersPlaceholder: "Input Assigners",
        WatchersPlaceholder: "Input Watchers",
        OwnerPlaceholder: "Input Owner",
        BreakdownReporterPlaceholder: "Input Breakdown Reported By",
        StartJobPlaceholder: "Input Start Job",
        Select: "Control+A",
        Delete: "Backspace",
        Assignees: "Workers",
        Assigners: "Managers",
        Watchers: "Supervisors",
        Owner: "Issuer",
        BreakdownReporter: "Reported By",
        StartJob: "Confirm Job",
        UpdateSuccess: "Label Meta Updated successfully!!",
    };

    export const list_data_source_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Confirm: "OK",
        },
        NamePlaceholder: "Input List Data Source Name",
        KeyPlaceholder: "Key",
        ValuePlaceholder:"Value",
        AddButtonLocator: "#screencontainer > div > app-list-data-source > div > div > nz-card > div.ant-card-body > form > div:nth-child(3) > div > nz-form-item > button > span.ng-star-inserted",
        key1: generateRandomString(10),
        Value1: generateRandomString(10),
        key2: generateRandomString(10),
        Value2: generateRandomString(10),
        key3: generateRandomString(10),
        Value3: generateRandomString(10),
        CreateSuccess: "List Data Source Added successfully!!",
        AddButtonOneLocator: "#screencontainer > div > app-list-data-source > div > div > nz-card > div.ant-card-body > form > div:nth-child(4) > div > nz-form-item > button > span.ng-star-inserted",
        Select: "Control+A",
        Delete: "Backspace",
        DataSourceNameAlert: "Please Input List Data Source Name!",
        DuplicateAlert: "Duplicate label name exist in list",
        Newkey1: generateRandomString(10),
        NewValue1: generateRandomString(10),
        Newkey2: generateRandomString(10),
        NewValue2: generateRandomString(10),
        Newkey3: generateRandomString(10),
        NewValue3: generateRandomString(10),
        UpdateKey: generateRandomString(10),
        UpdateSuccess: "List Data Source Updated successfully!!",
        DeleteSuccess: "List Data Source Removed successfully!!",
        DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
        DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']"
    };

    export const approval_matrix_map_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Confirm: "OK",
        },
        ApprovalMatrixLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        PlantLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        ApproverOneLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverTwoLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverThreeLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(3) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverFourLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(4) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverFiveLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(5) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        Enter: "Enter",
        Down: "ArrowDown",
        EditText: "Edit Matrix Map",
        CreateSuccess: "Approval Matrix Map Created Successfully!!",
        ApprovalMatrixCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        PlantCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApprovalMatrixAlert: "Please Select Approval Matrix!",
        PlantAlert: "Please Select Plant!",
        ApproverOneCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverTwoCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverThreeCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(3) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverFourCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(4) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverFiveCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(5) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverOneAlertLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > nz-form-item > nz-form-control",
        ApproverTwoAlertLocator: '#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > nz-form-item > nz-form-control',
        ApproverThreeAlertLocator: '#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(3) > td:nth-child(3) > nz-form-item > nz-form-control',
        ApproverFourAlertLocator: '#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(4) > td:nth-child(3) > nz-form-item > nz-form-control',
        ApproverFiveAlertLocator: '#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(5) > td:nth-child(3) > nz-form-item > nz-form-control',
        PaginationLocator: "#screencontainer > div > app-approval-matrix-map-dashboard > div > div > nz-card > div.ant-card-body > nz-table > nz-spin > div > nz-pagination > ul > li.ant-pagination-options.ng-star-inserted > nz-select > nz-select-top-control",
        ApprovalMatrixEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        PlantEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        ApproverOneEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverTwoEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverThreeEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(3) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverFourEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(4) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverFiveEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(5) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        UpdateSuccess: "Approval Matrix Map Updated Successfully!!",
        ApproverOneCancelEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        ApproverTwoCancelEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        ApproverThreeCancelEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(3) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        ApproverFourCancelEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(4) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        ApproverFiveCancelEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(5) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        DeleteSuccess: "Approval Matrix Map Deleted Successfully!!",
        DeleteLocatorPrefix: "tr.ant-table-row:has-text(",
        DeleteLocatorSuffix: ") button[ nztype='primary'][nzdanger='']",
        MapExistAlert: "Approval matrix map exist for plant",

    };

    export const breakdownTypeVariables = {
        operation: {
            create: "Add",
            save: "Save",
            cancel: "Cancel",
        },
        Placeholder: "Input Breakdown Type Name",
        CreateSuccess: "Breakdown Type Created Successfully!!",
        Select: "Control+A",
        Delete: "Backspace",
        Alert: "Please Input Breakdown Type Name!",
        BreakdownTypeExistAlert: "Breakdown Type Name Exist",
    };