image: node:20.10.0

pipelines:
  default:
    - step:
        name: Playwright Tests
        image: mcr.microsoft.com/playwright:v1.37.1-jammy
        script:
          - npm install
          # - Run the test cases
          - npm run test
